export const FETCH_ANSWER_REQUEST = 'FETCH_ANSWER_REQUEST'
export const FETCH_QUESTION_ANSWERS_SUCCESS = 'FETCH_QUESTION_ANSWERS_SUCCESS'
export const FETCH_USER_ANSWERS_SUCCESS = 'FETCH_USER_ANSWERS_SUCCESS'
export const FETCH_ANSWER_FAILURE = 'FETCH_ANSWER_FAILURE'